openapi: 3.0.1
info:
  title: Автомойка API
  description:  "учебное задание"
  version: 0.0.1
tags:
  - name: Пользователь
    description: Настройка аккаунта
  - name: Авто
    description: Управление автомобилями
  - name: Заказы
    description: Управление заказами
  - name: Автомойки
    description: Выбор автомойки
paths:
# post, put, delete, list
  /user:
      post:
        tags:
          - Пользователь
        summary: Создать пользователя
        description: This can only be done by the logged in user.
        operationId: createUser
        requestBody:
          description: Created user object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
            application/x-www-form-urlencoded:
              schema:
                $ref: '#/components/schemas/User'
        responses:
          default:
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/User'
              application/xml:
                schema:
                  $ref: '#/components/schemas/User'
  /user/{username}:
      delete:
        tags:
          - Пользователь
        summary: Delete user
        description: This can only be done by the logged in user.
        operationId: deleteUser
        parameters:
          - name: username
            in: path
            description: The name that needs to be deleted
            required: true
            schema:
              type: string
        responses:
          '400':
            description: Invalid username supplied
          '404':
            description: User not found
  /auto:
      post:
        tags:
        - Авто
        summary: Добавить авто
        description: Добавить новое авто
        operationId: createAuto
        requestBody:
            description: Created auto
            content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/Auto'
                  application/xml:
                    schema:
                      $ref: '#/components/schemas/Auto'
                  application/x-www-form-urlencoded:
                    schema:
                      $ref: '#/components/schemas/Auto'
        responses:
                default:
                  description: successful operation
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/Auto'
                    application/xml:
                      schema:
                        $ref: '#/components/schemas/Auto'
components:
  schemas:
    Auto:
      type: object
      properties:
          id:
            type: integer
            format: int64
            example: 1
          Userid:
            type: integer
            format: int64
            example: 1
          Brand:
            type: string
            example: Toyota
          Model:
            type: string
            example: Mark 2
          Number:
            type: string
            example: М123ЯУ
      xml:
        name: auto
    User:
        type: object
        properties:
          id:
            type: integer
            format: int64
            example: 1
          username:
            type: string
            example: linariell
          firstName:
            type: string
            example: Polina
          lastName:
            type: string
            example: Vitkovskaya
          email:
            type: string
            example: p.vitkovskaya@email.com
          password:
            type: string
            example: '12345'
          phone:
            type: string
            example: '12345'
        xml:
          name: user
  requestBodies:
    UserArray:
          description: List of user object
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
