openapi: 3.0.1
info:
  title: Автомойка API
  description:  "учебное задание"
  version: 0.0.1
tags:
  - name: user
    description: Operations about user
paths:
# post, put, delete, list
  /user:
      post:
        tags:
          - user
        summary: Create user
        description: This can only be done by the logged in user.
        operationId: createUser
        requestBody:
          description: Created user object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
            application/xml:
              schema:
                $ref: '#/components/schemas/User'
            application/x-www-form-urlencoded:
              schema:
                $ref: '#/components/schemas/User'
        responses:
          default:
            description: successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/User'
              application/xml:
                schema:
                  $ref: '#/components/schemas/User'
                
components:
  schemas:
    User:
        type: object
        properties:
          id:
            type: integer
            format: int64
            example: 1
          username:
            type: string
            example: linariell
          firstName:
            type: string
            example: Polina
          lastName:
            type: string
            example: Vitkovskaya
          email:
            type: string
            example: p.vitkovskaya@email.com
          password:
            type: string
            example: '12345'
          phone:
            type: string
            example: '12345'
        xml:
          name: user
